/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sincogpro.contenedor;

import com.sincogpro.administration.SocioPanel;
import com.sincogpro.consultas.ConsultaModeloSocio;
import com.sincogpro.controlador.ControladorContenedor;
import com.sincogpro.controlador.CRUDSOCIO;
import com.sincogpro.modelos.Socio;

/**
 *
 * @author RESAINVENTARIO
 */
public class FrmPrincipal extends javax.swing.JFrame {

    Socio modeloSocio = new Socio();
    SocioPanel sociopanel = new SocioPanel();
    ConsultaModeloSocio consultaSocio = new ConsultaModeloSocio();
    
    ControladorContenedor ctrlContenedor;
    CRUDSOCIO nuevoSocio;
    
    public FrmPrincipal() {
        initComponents();
        ctrlContenedor = new ControladorContenedor(this, sociopanel);
        nuevoSocio = new CRUDSOCIO(modeloSocio, consultaSocio, sociopanel){} ;
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContenedor = new javax.swing.JPanel();
        PLIZ = new javax.swing.JPanel();
        versociosBtn = new javax.swing.JButton();
        ocultarSociosBtn = new javax.swing.JButton();
        PLIF = new javax.swing.JPanel();
        licenseLabel = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelContenedor.setBackground(new java.awt.Color(153, 153, 153));
        PanelContenedor.setLayout(new java.awt.BorderLayout());

        PLIZ.setBackground(new java.awt.Color(204, 204, 204));

        versociosBtn.setText("Ver Socios");

        ocultarSociosBtn.setText("Ocultar Socios");

        javax.swing.GroupLayout PLIZLayout = new javax.swing.GroupLayout(PLIZ);
        PLIZ.setLayout(PLIZLayout);
        PLIZLayout.setHorizontalGroup(
            PLIZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PLIZLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PLIZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(versociosBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ocultarSociosBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                .addContainerGap())
        );
        PLIZLayout.setVerticalGroup(
            PLIZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PLIZLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(versociosBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ocultarSociosBtn)
                .addContainerGap(620, Short.MAX_VALUE))
        );

        PanelContenedor.add(PLIZ, java.awt.BorderLayout.WEST);

        PLIF.setBackground(new java.awt.Color(255, 255, 255));

        licenseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        licenseLabel.setText("sincogpro is developed by Lucas Andres Marsell (QueryBirdCode)");
        licenseLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 2));

        javax.swing.GroupLayout PLIFLayout = new javax.swing.GroupLayout(PLIF);
        PLIF.setLayout(PLIFLayout);
        PLIFLayout.setHorizontalGroup(
            PLIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PLIFLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(licenseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
                .addContainerGap())
        );
        PLIFLayout.setVerticalGroup(
            PLIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PLIFLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(licenseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelContenedor.add(PLIF, java.awt.BorderLayout.SOUTH);

        jMenu1.setText("File");
        menuBar.add(jMenu1);

        jMenu2.setText("Edit");
        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PLIF;
    public javax.swing.JPanel PLIZ;
    public javax.swing.JPanel PanelContenedor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JLabel licenseLabel;
    private javax.swing.JMenuBar menuBar;
    public javax.swing.JButton ocultarSociosBtn;
    public javax.swing.JButton versociosBtn;
    // End of variables declaration//GEN-END:variables
}
