/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sincogpro.administration;

import java.util.regex.Pattern;

/**
 *
 * @author RESAINVENTARIO
 */
public class SocioPanel extends javax.swing.JPanel {
    
    public SocioPanel() {
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultaModeloSocio1 = new com.sincogpro.consultas.ConsultaModeloSocio();
        entidadGrupo = new javax.swing.ButtonGroup();
        menuEmergente = new javax.swing.JPopupMenu();
        menu = new javax.swing.JMenu();
        editarSocio = new javax.swing.JMenuItem();
        FichaSocio = new javax.swing.JTabbedPane();
        ListaSocioPanel = new javax.swing.JPanel();
        EtiquetaTitulo = new javax.swing.JLabel();
        EtiquetaBusquedaSocio = new javax.swing.JLabel();
        CampoBusquedaSocio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSocioDT = new javax.swing.JTable();
        RegistroSocioPanel = new javax.swing.JPanel();
        razonSocialLbl = new javax.swing.JLabel();
        razonSocialTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        codigoSocioLbl = new javax.swing.JLabel();
        codigoSocioTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        razonComercialLbl = new javax.swing.JLabel();
        razonComercialTXt = new javax.swing.JTextField();
        cedulaLbl = new javax.swing.JLabel();
        cedulaTxt = new javax.swing.JTextField();
        rucLbl = new javax.swing.JLabel();
        rucTxt = new javax.swing.JTextField();
        direccionLbl = new javax.swing.JLabel();
        direccionTxt = new javax.swing.JTextField();
        telf1Lbl = new javax.swing.JLabel();
        telf1Txt = new javax.swing.JFormattedTextField();
        telf2Lbl = new javax.swing.JLabel();
        telf2Txt = new javax.swing.JFormattedTextField();
        email1Lbl = new javax.swing.JLabel();
        email1Txt = new javax.swing.JTextField();
        email2Lbl = new javax.swing.JLabel();
        email2Txt = new javax.swing.JTextField();
        creditoChk = new javax.swing.JCheckBox();
        limiteCreditoLbl = new javax.swing.JLabel();
        limiteCreditoTxt = new javax.swing.JTextField();
        descuentoLbl = new javax.swing.JLabel();
        regimenPagoLbl = new javax.swing.JLabel();
        regimenPagoCmb = new javax.swing.JComboBox<>();
        regimenCobroLbl = new javax.swing.JLabel();
        regimenCobroCmb = new javax.swing.JComboBox<>();
        activoChk = new javax.swing.JCheckBox();
        crearBtn = new javax.swing.JButton();
        editarBtn = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();
        guardarBtn = new javax.swing.JButton();
        descuentoCmb = new javax.swing.JComboBox<>();
        divisaDescuentoLbl = new javax.swing.JLabel();
        entidadLbl = new javax.swing.JLabel();
        entidadCmb = new javax.swing.JComboBox<>();
        tipoSocioLbl = new javax.swing.JLabel();
        tipoSocioCmb = new javax.swing.JComboBox<>();

        menu.setText("opciones");

        editarSocio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sincogpro/stf/edit16.png"))); // NOI18N
        editarSocio.setText("editarsocio");
        editarSocio.setToolTipText("");
        menu.add(editarSocio);

        menuEmergente.add(menu);

        ListaSocioPanel.setBackground(new java.awt.Color(255, 255, 255));

        EtiquetaTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EtiquetaTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaTitulo.setText("TABLA DE DATOS DE SOCIOS REGISTRADOS");

        EtiquetaBusquedaSocio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sincogpro/stf/search16.png"))); // NOI18N
        EtiquetaBusquedaSocio.setText("SEARCH:");

        CampoBusquedaSocio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CampoBusquedaSocio.setText("INGRESA UNA CADENA DE BUSQUEDA");
        CampoBusquedaSocio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CampoBusquedaSocioMousePressed(evt);
            }
        });
        CampoBusquedaSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoBusquedaSocioActionPerformed(evt);
            }
        });
        CampoBusquedaSocio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CampoBusquedaSocioKeyReleased(evt);
            }
        });

        tablaSocioDT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaSocioDT.setComponentPopupMenu(menuEmergente);
        tablaSocioDT.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablaSocioDT.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tablaSocioDT);

        javax.swing.GroupLayout ListaSocioPanelLayout = new javax.swing.GroupLayout(ListaSocioPanel);
        ListaSocioPanel.setLayout(ListaSocioPanelLayout);
        ListaSocioPanelLayout.setHorizontalGroup(
            ListaSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaSocioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ListaSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(EtiquetaTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
                    .addGroup(ListaSocioPanelLayout.createSequentialGroup()
                        .addComponent(EtiquetaBusquedaSocio)
                        .addGap(18, 18, 18)
                        .addComponent(CampoBusquedaSocio)))
                .addContainerGap())
        );
        ListaSocioPanelLayout.setVerticalGroup(
            ListaSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaSocioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EtiquetaTitulo)
                .addGap(18, 18, 18)
                .addGroup(ListaSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaBusquedaSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoBusquedaSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                .addContainerGap())
        );

        FichaSocio.addTab("REGISTROS", ListaSocioPanel);

        RegistroSocioPanel.setBackground(new java.awt.Color(255, 255, 255));

        razonSocialLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        razonSocialLbl.setText("RAZON SOCIAL:");

        razonSocialTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        razonSocialTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                razonSocialTxtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FICHA REGISTRO Y EDICION DE DATOS DE SOCIO");

        codigoSocioLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        codigoSocioLbl.setText("CODIGO SOCIO:");

        codigoSocioTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        razonComercialLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        razonComercialLbl.setText("RAZON COMERCIAL:");

        razonComercialTXt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        razonComercialTXt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                razonComercialTXtActionPerformed(evt);
            }
        });

        cedulaLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cedulaLbl.setText("CEDULA:");

        cedulaTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cedulaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaTxtActionPerformed(evt);
            }
        });

        rucLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rucLbl.setText("RUC/NIT:");

        rucTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rucTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rucTxtActionPerformed(evt);
            }
        });

        direccionLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        direccionLbl.setText("DIRECCION:");

        direccionTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        direccionTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionTxtActionPerformed(evt);
            }
        });

        telf1Lbl.setText("TELF1:");

        try {
            telf1Txt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telf1Txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        telf2Lbl.setText("TELF2:");

        try {
            telf2Txt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telf2Txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        email1Lbl.setText("EMAIL1:");

        email1Txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        email2Lbl.setText("EMAIL2:");

        email2Txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        creditoChk.setText("CREDITO");

        limiteCreditoLbl.setText("LIMITE CREDITO:");

        limiteCreditoTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        descuentoLbl.setText("DESCUENTO:");

        regimenPagoLbl.setText("REG PAGO:");

        regimenCobroLbl.setText("REG COBRO:");

        activoChk.setText("ACTIVO");

        crearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sincogpro/stf/add32.png"))); // NOI18N
        crearBtn.setText("CREAR");

        editarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sincogpro/stf/edit32.png"))); // NOI18N
        editarBtn.setText("EDITAR");

        cancelarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sincogpro/stf/cancel32.png"))); // NOI18N
        cancelarBtn.setText("CANCELAR");

        guardarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sincogpro/stf/save32.png"))); // NOI18N
        guardarBtn.setText("GUARDAR");

        divisaDescuentoLbl.setText("USD");

        entidadLbl.setText("ENTIDAD:");

        tipoSocioLbl.setText("TIPOSOCIO:");

        javax.swing.GroupLayout RegistroSocioPanelLayout = new javax.swing.GroupLayout(RegistroSocioPanel);
        RegistroSocioPanel.setLayout(RegistroSocioPanelLayout);
        RegistroSocioPanelLayout.setHorizontalGroup(
            RegistroSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroSocioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(RegistroSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RegistroSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(RegistroSocioPanelLayout.createSequentialGroup()
                            .addGroup(RegistroSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(razonComercialLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(RegistroSocioPanelLayout.createSequentialGroup()
                                    .addGroup(RegistroSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cedulaLbl)
                                        .addGroup(RegistroSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(codigoSocioLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(razonSocialLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(rucLbl))
                                    .addGap(20, 20, 20)))
                            .addGap(18, 18, 18)
                            .addGroup(RegistroSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cedulaTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(codigoSocioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(razonSocialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(razonComercialTXt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rucTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(RegistroSocioPanelLayout.createSequentialGroup()
                                    .addComponent(entidadCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tipoSocioLbl)
                                    .addGap(18, 18, 18)
                                    .addComponent(tipoSocioCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(RegistroSocioPanelLayout.createSequentialGroup()
                            .addGroup(RegistroSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(direccionLbl)
                                .addComponent(telf1Lbl)
                                .addComponent(email1Lbl)
                                .addComponent(creditoChk)
                                .addComponent(activoChk))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(RegistroSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(direccionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistroSocioPanelLayout.createSequentialGroup()
                                    .addGroup(RegistroSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(email1Txt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(telf1Txt)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, RegistroSocioPanelLayout.createSequentialGroup()
                                            .addComponent(limiteCreditoLbl)
                                            .addGap(18, 18, 18)
                                            .addComponent(limiteCreditoTxt)
                                            .addGap(18, 18, 18)
                                            .addComponent(divisaDescuentoLbl))
                                        .addGroup(RegistroSocioPanelLayout.createSequentialGroup()
                                            .addComponent(regimenPagoLbl)
                                            .addGap(18, 18, 18)
                                            .addComponent(regimenPagoCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGap(18, 18, 18)
                                    .addGroup(RegistroSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(RegistroSocioPanelLayout.createSequentialGroup()
                                            .addComponent(telf2Lbl)
                                            .addGap(18, 18, 18)
                                            .addComponent(telf2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(RegistroSocioPanelLayout.createSequentialGroup()
                                            .addComponent(email2Lbl)
                                            .addGap(18, 18, 18)
                                            .addComponent(email2Txt))
                                        .addGroup(RegistroSocioPanelLayout.createSequentialGroup()
                                            .addComponent(descuentoLbl)
                                            .addGap(18, 18, 18)
                                            .addComponent(descuentoCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(RegistroSocioPanelLayout.createSequentialGroup()
                                            .addComponent(regimenCobroLbl)
                                            .addGap(18, 18, 18)
                                            .addComponent(regimenCobroCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGroup(RegistroSocioPanelLayout.createSequentialGroup()
                                    .addComponent(crearBtn)
                                    .addGap(18, 18, 18)
                                    .addComponent(editarBtn)
                                    .addGap(18, 18, 18)
                                    .addComponent(cancelarBtn)
                                    .addGap(18, 18, 18)
                                    .addComponent(guardarBtn)))))
                    .addComponent(entidadLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        RegistroSocioPanelLayout.setVerticalGroup(
            RegistroSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroSocioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegistroSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addGroup(RegistroSocioPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37)
                        .addGroup(RegistroSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(entidadLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entidadCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoSocioLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoSocioCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(RegistroSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codigoSocioLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigoSocioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(RegistroSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(razonSocialLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(razonSocialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(RegistroSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(razonComercialLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(razonComercialTXt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(RegistroSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cedulaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cedulaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(RegistroSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rucLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rucTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(RegistroSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(direccionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(direccionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(RegistroSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telf1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telf1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telf2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telf2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(RegistroSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(RegistroSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(creditoChk)
                            .addComponent(limiteCreditoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(limiteCreditoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descuentoLbl)
                            .addComponent(descuentoCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(divisaDescuentoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(RegistroSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(regimenPagoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(regimenPagoCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(regimenCobroLbl)
                            .addComponent(regimenCobroCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(activoChk))
                        .addGap(33, 33, 33)
                        .addGroup(RegistroSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(crearBtn)
                            .addComponent(editarBtn)
                            .addComponent(cancelarBtn)
                            .addComponent(guardarBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)))
                .addContainerGap())
        );

        FichaSocio.addTab("FICHA PERSONA", RegistroSocioPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FichaSocio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FichaSocio)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CampoBusquedaSocioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoBusquedaSocioMousePressed
        
    }//GEN-LAST:event_CampoBusquedaSocioMousePressed

    private void CampoBusquedaSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoBusquedaSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoBusquedaSocioActionPerformed

    private void CampoBusquedaSocioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoBusquedaSocioKeyReleased
        
    }//GEN-LAST:event_CampoBusquedaSocioKeyReleased

    private void razonSocialTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_razonSocialTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_razonSocialTxtActionPerformed

    private void razonComercialTXtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_razonComercialTXtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_razonComercialTXtActionPerformed

    private void cedulaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaTxtActionPerformed

    private void rucTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rucTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rucTxtActionPerformed

    private void direccionTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField CampoBusquedaSocio;
    private javax.swing.JLabel EtiquetaBusquedaSocio;
    private javax.swing.JLabel EtiquetaTitulo;
    public javax.swing.JTabbedPane FichaSocio;
    private javax.swing.JPanel ListaSocioPanel;
    private javax.swing.JPanel RegistroSocioPanel;
    public javax.swing.JCheckBox activoChk;
    public javax.swing.JButton cancelarBtn;
    private javax.swing.JLabel cedulaLbl;
    public javax.swing.JTextField cedulaTxt;
    private javax.swing.JLabel codigoSocioLbl;
    public javax.swing.JTextField codigoSocioTxt;
    private com.sincogpro.consultas.ConsultaModeloSocio consultaModeloSocio1;
    public javax.swing.JButton crearBtn;
    public javax.swing.JCheckBox creditoChk;
    public javax.swing.JComboBox<String> descuentoCmb;
    private javax.swing.JLabel descuentoLbl;
    private javax.swing.JLabel direccionLbl;
    public javax.swing.JTextField direccionTxt;
    private javax.swing.JLabel divisaDescuentoLbl;
    public javax.swing.JButton editarBtn;
    public javax.swing.JMenuItem editarSocio;
    private javax.swing.JLabel email1Lbl;
    public javax.swing.JTextField email1Txt;
    private javax.swing.JLabel email2Lbl;
    public javax.swing.JTextField email2Txt;
    public javax.swing.JComboBox<String> entidadCmb;
    private javax.swing.ButtonGroup entidadGrupo;
    private javax.swing.JLabel entidadLbl;
    public javax.swing.JButton guardarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel limiteCreditoLbl;
    public javax.swing.JTextField limiteCreditoTxt;
    private javax.swing.JMenu menu;
    private javax.swing.JPopupMenu menuEmergente;
    private javax.swing.JLabel razonComercialLbl;
    public javax.swing.JTextField razonComercialTXt;
    private javax.swing.JLabel razonSocialLbl;
    public javax.swing.JTextField razonSocialTxt;
    public javax.swing.JComboBox<String> regimenCobroCmb;
    private javax.swing.JLabel regimenCobroLbl;
    public javax.swing.JComboBox<String> regimenPagoCmb;
    private javax.swing.JLabel regimenPagoLbl;
    private javax.swing.JLabel rucLbl;
    public javax.swing.JTextField rucTxt;
    public javax.swing.JTable tablaSocioDT;
    private javax.swing.JLabel telf1Lbl;
    public javax.swing.JFormattedTextField telf1Txt;
    private javax.swing.JLabel telf2Lbl;
    public javax.swing.JFormattedTextField telf2Txt;
    public javax.swing.JComboBox<String> tipoSocioCmb;
    private javax.swing.JLabel tipoSocioLbl;
    // End of variables declaration//GEN-END:variables
}
