/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sincogpro.administration;

import com.sincogpro.controlador.ControladorSocio;
import java.util.regex.Pattern;

/**
 *
 * @author RESAINVENTARIO
 */
public class SocioPanel extends javax.swing.JPanel {
    
   
    Pattern pattern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                        + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
    
    
    public SocioPanel() {
        initComponents();
    }
    
    
    
 
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FichasPanel = new javax.swing.JTabbedPane();
        ListaSocioPanel = new javax.swing.JPanel();
        EtiquetaTitulo = new javax.swing.JLabel();
        EtiquetaBusquedaSocio = new javax.swing.JLabel();
        CampoBusquedaSocio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaSocio = new javax.swing.JTable();
        RegistroSocioPanel = new javax.swing.JPanel();

        ListaSocioPanel.setBackground(new java.awt.Color(255, 255, 255));

        EtiquetaTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EtiquetaTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaTitulo.setText("TABLA DE DATOS DE PERSONAS REGISTRADAS");

        EtiquetaBusquedaSocio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sincogpro/stf/search16.png"))); // NOI18N
        EtiquetaBusquedaSocio.setText("SEARCH:");

        CampoBusquedaSocio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CampoBusquedaSocio.setText("INGRESA UNA CADENA DE BUSQUEDA");
        CampoBusquedaSocio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CampoBusquedaSocioMousePressed(evt);
            }
        });
        CampoBusquedaSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoBusquedaSocioActionPerformed(evt);
            }
        });
        CampoBusquedaSocio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CampoBusquedaSocioKeyReleased(evt);
            }
        });

        TablaSocio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaSocio);

        javax.swing.GroupLayout ListaSocioPanelLayout = new javax.swing.GroupLayout(ListaSocioPanel);
        ListaSocioPanel.setLayout(ListaSocioPanelLayout);
        ListaSocioPanelLayout.setHorizontalGroup(
            ListaSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListaSocioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ListaSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EtiquetaTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ListaSocioPanelLayout.createSequentialGroup()
                        .addComponent(EtiquetaBusquedaSocio)
                        .addGap(18, 18, 18)
                        .addComponent(CampoBusquedaSocio)))
                .addContainerGap())
        );
        ListaSocioPanelLayout.setVerticalGroup(
            ListaSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaSocioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EtiquetaTitulo)
                .addGap(18, 18, 18)
                .addGroup(ListaSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaBusquedaSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoBusquedaSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addContainerGap())
        );

        FichasPanel.addTab("REGISTROS", ListaSocioPanel);

        RegistroSocioPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout RegistroSocioPanelLayout = new javax.swing.GroupLayout(RegistroSocioPanel);
        RegistroSocioPanel.setLayout(RegistroSocioPanelLayout);
        RegistroSocioPanelLayout.setHorizontalGroup(
            RegistroSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 869, Short.MAX_VALUE)
        );
        RegistroSocioPanelLayout.setVerticalGroup(
            RegistroSocioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        FichasPanel.addTab("FICHA PERSONA", RegistroSocioPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FichasPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FichasPanel)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CampoBusquedaSocioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoBusquedaSocioMousePressed
        
    }//GEN-LAST:event_CampoBusquedaSocioMousePressed

    private void CampoBusquedaSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoBusquedaSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoBusquedaSocioActionPerformed

    private void CampoBusquedaSocioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoBusquedaSocioKeyReleased
        
    }//GEN-LAST:event_CampoBusquedaSocioKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField CampoBusquedaSocio;
    private javax.swing.JLabel EtiquetaBusquedaSocio;
    private javax.swing.JLabel EtiquetaTitulo;
    private javax.swing.JTabbedPane FichasPanel;
    private javax.swing.JPanel ListaSocioPanel;
    private javax.swing.JPanel RegistroSocioPanel;
    public javax.swing.JTable TablaSocio;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
